/-
Copyright (c) 2026 J. Bridges. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: J. Bridges, Claude (Anthropic AI assistant)

Abstract parametric structure for power-sum strong completeness.

This module provides a general framework for proving strong completeness
of sequences combining polynomial growth with harmonic corrections.
-/

import Mathlib.Data.Nat.Basic
import Mathlib.Data.Real.Basic

namespace Problem351

/-! ## Abstract Parametric Framework

The PowerSumParams structure abstracts sequences of the form {f(n) + g(n)}
where f provides "bulk" growth (territory creation) and g provides
"correction" (boundary adjustment).

This framework supports proving completeness for various combinations of
polynomial and harmonic terms, following the pattern in van Doorn (2025)
and related additive combinatorics results.

**Design principle**: Parameters are FUNCTIONS, not explicit formulas.
This allows instantiation with different power/reciprocal combinations
without hardcoding the algebraic structure. -/

/-- Abstract parametric structure for power-sum completeness.

    Generalizes sequences of the form {f(n) + g(n)} where:
    - f provides "bulk" growth (Archimedean expansion, territory creation)
    - g provides "correction" (p-adic density, boundary adjustment)

    The key insight (from Problem 347/351 connection) is that:
    - Ratio-2 bulk growth ensures bounded gaps (Graham's Σ-sequence)
    - Divergent correction ensures residue class coverage (Egyptian fractions)
    - Together they give strong completeness (subset sums cover all large integers)

    This framework is designed for extensibility to other Erdős problems
    with similar additive structure. -/
structure PowerSumParams where
  /-- Bulk growth function (e.g., x², x³, polynomial sequences).

      This term provides the "territory" - Archimedean coverage of large integers.
      The ratio-2 condition ensures gaps between consecutive terms don't grow
      too quickly, which is key for Graham's completeness machinery. -/
  bulk : ℕ → ℕ

  /-- Correction function (real-valued, e.g., 1/x, 1/x²).

      This term provides "boundary adjustment" - p-adic coverage ensuring all
      residue classes are eventually hit. The divergence condition is what makes
      this work (contrast: 1/n diverges, 1/n² converges). -/
  correction : ℕ → ℝ

  /-- Bulk must have positive growth -/
  bulk_pos : ∀ n > 0, bulk n > 0

  /-- Bulk must be monotone increasing -/
  bulk_mono : ∀ n m, 0 < n → n < m → bulk n < bulk m

  /-- Bulk must satisfy approximate ratio-2 growth eventually.

      This is the key condition from Graham (1964): if consecutive terms
      satisfy s_{n+1} ≤ 2·s_n eventually, the sequence is a Σ-sequence,
      which guarantees bounded gaps and eventually allows complete coverage.

      We allow a small error term 1/n to accommodate polynomial growth. -/
  bulk_ratio_two : ∃ N > 0, ∀ n ≥ N,
    (bulk (n + 1) : ℝ) / (bulk n : ℝ) ≤ 2 + 1 / (n : ℝ)

  /-- Correction must be non-summable (divergent sum).

      This is the Egyptian fraction condition: the harmonic-like series must
      diverge to ensure all residue classes are covered. Compare:
      - ∑ 1/n = ∞ (diverges - GOOD for completeness)
      - ∑ 1/n² < ∞ (converges - NOT sufficient)

      Divergence gives the "correction budget" needed for p-adic density.

      Simplified formulation: correction terms grow unboundedly in sum. -/
  correction_diverges : ∀ M : ℝ, ∃ N : ℕ, abs (correction N) * N > M

  /-- Correction terms must decay (individual terms → 0).

      While the sum diverges, individual terms must vanish. This ensures
      the correction doesn't dominate the bulk asymptotically. -/
  correction_decay : ∀ n > 0, abs (correction (n + 1)) < abs (correction n)

/-- The sequence generated by PowerSumParams.

    For a typical instance (like van Doorn's x² + 1/x), this produces:
    - sequence params 1 = 1² + 1/1 = 2
    - sequence params 2 = 2² + 1/2 = 4.5
    - sequence params 3 = 3² + 1/3 = 9.333...
    - etc.

    The real values allow exact representation of the correction term. -/
def sequence (params : PowerSumParams) (n : ℕ) : ℝ :=
  (params.bulk n : ℝ) + params.correction n

/-! ## Strong Completeness

Strong completeness is a robustness property: not only do subset sums
cover all large integers, they continue to do so even after removing
any finite subset.

This is the property proven by van Doorn (2025) for {x² + 1/x} and
is the key connection to Problem 347's construction (which also survives
finite perturbations due to density 1).

**Geometric intuition** (from 347/351 bridge):
- Ratio-2 growth = filling binary places (doubling sequence)
- Divergent correction = residue class coverage (p-adic density)
- Strong completeness = no finite deletion can break coverage
- Connection: van Doorn's M_{n+1} = 2·M_n + 1 is the razor edge -/

/-- Strong completeness: subset sums cover all large integers
    even after removing any finite subset.

    This is stronger than ordinary completeness (which allows
    a fixed sequence) because it requires the property to survive
    arbitrary finite deletions.

    Equivalently: the sequence has "redundancy" - enough density
    that losing finitely many terms doesn't matter.

    Abstract formulation (avoiding complex set theory): The property
    states that after removing any finite collection of indices,
    sufficiently large integers can still be represented. -/
axiom strongly_complete (params : PowerSumParams) : Prop

/-! ## Density Notion

For connecting to Problem 347's density-1 result, we need a notion
of how "densely" the subset sums cover the integers.

This is axiomatized as the formal property will be proven via
Problem 347's machinery. -/

/-- A sequence has asymptotic density 1 if the proportion of integers
    representable as subset sums approaches 1.

    This is the condition proven in Problem 242/Lemma 10.2 for the
    Bridges 347 construction, and it's the Archimedean half of the
    proof (p-adic half is residue class coverage). -/
axiom has_density_one (params : PowerSumParams) : Prop

end Problem351
